{% set name = "dbt-databricks" %}
{% set version = "1.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bd9ce223eb241aa0fad82a790a1ac962db48d6a4e7830a30eb1d5878e58db7e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - databricks-sdk ==0.17.0
    - databricks-sql-connector >=3.5.0,<4.0.0
    - dbt-adapters >=1.7.0,<2.0
    - dbt-common >=1.10.0,<2.0
    - dbt-core >=1.8.7,<2.0
    - dbt-spark >=1.8.0,<2.0
    - keyring >=23.13.0
    - pandas <2.2.0
    - pydantic >=1.10.0,<2

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/databricks/dbt-databricks
  summary: The Databricks adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - monaldoj
