{% set name = "dbt-databricks" %}
{% set version = "1.7.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-databricks-{{ version }}.tar.gz
  sha256: 60a95e686c049d9695e7bc80e8af4191677fe35454d62787000a5481bba244e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dbt-spark >=1.7.1,<1.8
    - databricks-sql-connector >=2.9.3,<3.0.0
    - databricks-sdk ==0.17.0
    - keyring >=23.13.0
    - pandas <2.2.0
    - protobuf <5.0.0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/databricks/dbt-databricks
  summary: The Databricks adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - monaldoj
