{% set name = "dbt-databricks" %}
{% set version = "1.10.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 38cdbaff0f02e922bf5e54c31fcd15ee04349c29a3875ac4a0500076da94593f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - databricks-sdk >=0.41,<0.64.0
    - databricks-sql-connector >=4.0.0,<4.0.6
    - dbt-adapters >=1.16.0,<1.16.5
    - dbt-common >=1.24.0,<1.29.0
    - dbt-core >=1.10.1,<1.10.10
    - dbt-spark >=1.9.0,<1.9.4
    - keyring >=23.13.0
    - pydantic >=1.10.0

test:
  imports:
    - dbt.adapters.databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/databricks/dbt-databricks
  summary: The Databricks adapter plugin for dbt
  license: Apache-2.0
  license_family: Apache
  license_file: License.md
  description: |
    The dbt-databricks adapter contains all of the code enabling dbt to work with Databricks.
    This adapter is based off the amazing work done in dbt-spark.
  dev_url: https://github.com/databricks/dbt-databricks
  doc_url: https://docs.getdbt.com/reference/resource-configs/databricks-configs

extra:
  recipe-maintainers:
    - monaldoj
